services:
  load-balance:
      image: nginx:latest
      deploy:
        resources:
          limits:
            cpus: "0.5"
            memory: "15MB"

  server:
    image:
    deploy:
        resources:
          limits:
            cpus: "0.5"
            memory: "100MB"
